### ISSUE TITLE
[crudless.yml] 列表状态栏，增加颜色配置项

### ISSUE THREAD

**Issue by h89916300** [kequandian/hub.crudless.zerocode#18]
#yml配置格式如下
```
# status 选项字段
    status:
        label: 状态
        type: select
        options:
          OPEN: 
              label: 开放
              color: #1890ff
          DRAFT: 
              label: 草稿
              color: #1890ff
        scope: #  不能直接编辑状态
          - list
          - view
          - new
          - edit
```
#对应的json 代码位置
```
"tableFields": [
        {
            "label": "状态", 
            "field": "status", 
            "valueType": "tag", 
            "options": {
                "map": {
                    "open": "开启", 
                    "submit": "提交", 
                    "underview": "审核", 
                    "close": "关闭"
                }, 
                "color": {
                    "open": "#1890ff", 
                    "submit": "#1891ff", 
                    "underview": "#1892ff", 
                    "close": "#1893ff"
                }
            }
        }, 
    ], 
```

#如何去掉列表tag背景色，如 性别栏
![image](https://user-images.githubusercontent.com/35095695/92347108-806b5300-f101-11ea-8226-fba0c9e3b54b.png)
