### ISSUE TITLE
pages  -> fields -> 字段信息 -> scope中的适配范围不全，e.g. all...

### ISSUE THREAD

**Issue by zchengb** [kequandian/hub.crudless.zerocode#2]

**Comment by zchengb** [comment]
```yaml
service_category:
        lable: 服务类别
        type: select-fetch
        scope:
          - all
        options:
          API: /api/crud/service/category
```
上述`scope`中的`- all`无效，待完善
