### ISSUE TITLE
[crudless.yml] sql > default, 如果配置时间默认值

### ISSUE THREAD

**Issue by h89916300** [kequandian/hub.crudless.zerocode#20]
```
sql:
    type: timestamp
    notnull: true
    comment: "创建时间"
    default: CURRENT_TIMESTAMP
    unique: false
```
其中 default 值为 CURRENT_TIMESTAMP 或者 NOW，运行yml会报错
报错信息: 
    UnhandledPromiseRejectionWarning: YAMLSyntaxError: All collection items must start at the same column
