### ISSUE TITLE
[crudless.yml] 必填字段格式

### ISSUE THREAD

**Issue by h89916300** [kequandian/hub.crudless.zerocode#21]
#yml配置格式如下
```
tips: 请输入名称   # required: message 由tips 转换
rules: 
  - required
  - phone
```
#对应的json 代码位置
```
"createFields": [
    {
        "label": "名称", 
        "props": {
            "placeholder": "请输入"
        }, 
        "rules": [
            {
                "type": "required",
                "message": "请填写名称"
            }
        ], 
        "type": "input", 
        "field": "name"
    }, 
]
```

**Comment by youyeke** [comment]
直接在 yaml 原有的 `rules` 里面配置, 无需额外提供一个 `tips`
```yaml
rules: 
  - 
    type: required
    message: 请填写名称
  - phone
```
