### ISSUE TITLE
[crudless.yml] 按钮属性 actions 格式定义

### ISSUE THREAD

**Issue by h89916300** [kequandian/hub.crudless.zerocode#23]
#yml配置格式如下
#### scope 属性，控制按钮位置: 
- top:  列表操作(如新增，导出)
- item:  列表项操作(编辑，删除) 【默认】
- batch： 批量操作
```
actions:
  - 
    title: 导出
    type: export-excel
    api: /api/io/excel/teamReward
    data: teamReward    # 初始化数据，如生成 sql 插入语句
    scope: top 
  - 
    title: 新建
    type: path   # 通过路径跳转而且调用API
    path: 'myPage/myPage-add'
    scope: top
  -
    title: 提交
    type: meta   #  通过元操作（实际是调用固有API）
    # scope:  item  # 无需配置（默认值）
  - 
    title: 转换
    type: request
    outside: true
    api: /api/crud/undefined  # method 默认为 POST
    expect:    #  满足条件出现
        field: status,
        value: Draft
```
#对应的json 代码位置
```
#  scope: top 
actions: [
    {
        title: '导出 Excel',
        type: 'export-excel',
        options: {
            API:'/api/io/excel/teamReward'
        }
    },
    {
        title: '新增', 
        type: 'path',
        options: {
            path: 'myPage/myPage-add',
        },
    }
],

#  scope: item
operation: [
    {
        title: '开放', 
        type: 'request',
        options:{
            outside: true,
            API: '',
            method: 'post'
        },
        expect: {
            field: 'status',
            value: 'DRAFT'
        }
    },
```
