### ISSUE TITLE
[crudless.yml] 搜索字段 search属性 格式定义

### ISSUE THREAD

**Issue by h89916300** [kequandian/hub.crudless.zerocode#24]
#yml配置格式如下
```
list:
  search:   # 搜索条件
    fields
      -     
        label:  搜索
	field: search
	type: input
```
#对应的json 代码位置
```
{
  component: 'Search',
  config: {
    fields: [
      { label: '搜索', field: 'search', type: 'input' },
    ],
  }
}
```

#新组建配置，根据状态条件搜索栏，yml格式 
```
list:
  search:   # 搜索条件
    tab: # 展开分类
      field: status
      all: default # default 默认包括全部选项, none 代表没有全部选项
      options:
        Open: 打开
        Draft: 草稿
```
样式风格如下图
![image](https://user-images.githubusercontent.com/35095695/92342175-99b8d300-f0f2-11ea-895d-bd05447afe84.png)
