### ISSUE TITLE
[crudless.yml] 新增 dev_name 属性

### ISSUE THREAD

**Issue by h89916300** [kequandian/hub.crudless.zerocode#25]
#yml配置格式如下
```
entries:
  -   
    dev_name: product_mgr   # 用于装配服务时定位菜单入口
    label: 产品管理
    path: /products
    icon: static/product_entry.png   # 服务组可配置图标
    #app_id: demo  # 用于授权 (暂时忽略)
    #app_secret: AJOI7800AFJEO7AOFE   # 用于授权 (暂时忽略)
    sub_entries:
      -
        dev_name: product_type
        path: /products/types
        label: 产品分类
        #app_id: demo  # 用于授权 (暂时忽略)
        #app_secret: AJOI7800AFJEO7AOFE   # 用于授权 (暂时忽略)
```

: dev_name 忽略
