### ISSUE TITLE
定义配置与业务角色生成sql语句

### ISSUE THREAD

**Issue by a30f49** [kequandian/hub.crudless.zerocode#29]
1. 实施配置定义
```
data:
    field-config 
```

2. 实施角色定义, 审批流如何定义
```
data:
    roles:
       - name: 服务
          value:  assistant_id
          index: 1
       - name: 商务
          value:  businessman_id
          index: 2
```
