### ISSUE TITLE
定义报表 生成前后端代码

### ISSUE THREAD

**Issue by a30f49** [kequandian/hub.crudless.zerocode#31]
在crudless.xml 中定义报表 page
````
pages:
    issue_report:
        title: 
            table:  问题汇总
        data: 
            sql:  
        entry_name:  products
```
生成前后端代码可测试， 并提供 sandbox 测试环境
